--- #YAML:1.0
name:               Test-WWW-Mechanize-PSGI
version:            0.35
abstract:           Test PSGI programs using WWW::Mechanize
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Message::PSGI:  0
    Test::More:           0
    Test::WWW::Mechanize:  0
    Try::Tiny:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
